# Generated by Django 5.2.8 on 2025-11-11 22:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RateLimitEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique batch identifier",
                    ),
                ),
                (
                    "agent_count",
                    models.IntegerField(help_text="Number of agents in batch"),
                ),
                (
                    "delay_seconds",
                    models.FloatField(help_text="Delay applied (seconds)"),
                ),
                (
                    "initiated_by",
                    models.CharField(
                        help_text="Who initiated the batch", max_length=100
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "rate_limit_events",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Agent name (e.g., MAIN_AGENT)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "directory_path",
                    models.CharField(
                        help_text="Absolute path to agent's directory", max_length=500
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        help_text="Agent's role/responsibility", max_length=200
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("core", "Core"),
                            ("infrastructure", "Infrastructure"),
                            ("support", "Support"),
                            ("executive", "Executive"),
                            ("other", "Other"),
                        ],
                        help_text="Agent category",
                        max_length=50,
                    ),
                ),
                (
                    "zellij_session_name",
                    models.CharField(
                        help_text="Zellij session name (lowercase)", max_length=100
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, help_text="Is Zellij session currently active?"
                    ),
                ),
                (
                    "last_activated",
                    models.DateTimeField(
                        blank=True, help_text="Last activation timestamp", null=True
                    ),
                ),
                (
                    "pending_messages",
                    models.IntegerField(
                        default=0, help_text="Count of unread communications"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "agents",
                "ordering": ["category", "name"],
                "indexes": [
                    models.Index(fields=["name"], name="agents_name_6f5710_idx"),
                    models.Index(fields=["category"], name="agents_categor_b01ecf_idx"),
                    models.Index(
                        fields=["is_active"], name="agents_is_acti_3fbec7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Communication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_agent",
                    models.CharField(
                        db_index=True, help_text="Sender agent name", max_length=100
                    ),
                ),
                (
                    "to_agent",
                    models.CharField(
                        db_index=True, help_text="Recipient agent name", max_length=100
                    ),
                ),
                (
                    "subject",
                    models.CharField(help_text="Communication subject", max_length=200),
                ),
                ("content", models.TextField(help_text="Full markdown content")),
                (
                    "file_path",
                    models.CharField(
                        help_text="Absolute path to .md file",
                        max_length=500,
                        unique=True,
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA256 hash of file content",
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unread", "Unread"),
                            ("read", "Read"),
                            ("archived", "Archived"),
                        ],
                        default="unread",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(help_text="File creation timestamp"),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, help_text="When marked as read", null=True
                    ),
                ),
            ],
            options={
                "db_table": "communications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["from_agent", "to_agent"],
                        name="communicati_from_ag_4afd75_idx",
                    ),
                    models.Index(
                        fields=["status"], name="communicati_status_3c4fa3_idx"
                    ),
                    models.Index(
                        fields=["priority"], name="communicati_priorit_3972e7_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="communicati_created_68dcb3_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TODO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, help_text="Full TODO.txt content"),
                ),
                (
                    "line_count",
                    models.IntegerField(
                        default=0, help_text="Number of lines in TODO.txt"
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        help_text="Absolute path to TODO.txt", max_length=500
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(help_text="SHA256 hash of content", max_length=64),
                ),
                (
                    "last_synced",
                    models.DateTimeField(
                        auto_now=True, help_text="Last sync from file system"
                    ),
                ),
                (
                    "agent",
                    models.OneToOneField(
                        help_text="Agent this TODO belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="todo",
                        to="cacs.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "TODO",
                "verbose_name_plural": "TODOs",
                "db_table": "todos",
            },
        ),
        migrations.CreateModel(
            name="Activation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activated_by",
                    models.CharField(
                        help_text="Who/what triggered activation (HITL, MAIN_AGENT, etc)",
                        max_length=100,
                    ),
                ),
                (
                    "activation_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual (Web UI)"),
                            ("api", "API Call"),
                            ("batch", "Batch Activation"),
                            ("scheduled", "Scheduled"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("command_sent", models.TextField(help_text="Command sent to Zellij")),
                (
                    "success",
                    models.BooleanField(help_text="Was activation successful?"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, help_text="Error message if failed"),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "agent",
                    models.ForeignKey(
                        help_text="Agent that was activated",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activations",
                        to="cacs.agent",
                    ),
                ),
            ],
            options={
                "db_table": "activations",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["agent", "-timestamp"],
                        name="activations_agent_i_de07e3_idx",
                    ),
                    models.Index(
                        fields=["success"], name="activations_success_e14a08_idx"
                    ),
                ],
            },
        ),
    ]
